version: '3.1'
services:
  track-debts-dev-pg:
    image: postgres:10
    environment:
      POSTGRES_DB: track-debts
    volumes:
    - "./data:/var/lib/postgresql/data/"
    ports:
    - 5433:5432
  track-debts-test-pg:
    image: postgres:10
    environment:
      POSTGRES_DB: track-debts-test
    ports:
    - 5434:5432